### ISSUE TITLE
通过替换文件使aliyunsdkcore支持python3

### ISSUE THREAD

**Issue by kant-li** [duangy/aliyunsdkcore#1]
直接把这些文件放项目中还是比较难看的。

如果已经安装这个模块（比如2.3.5或2.4.4版本，虽然官网号称支持python3.x，其实根本没做支持，包括各种print的用法都还是2.x版本的），可以直接将安装后的文件替换掉。

比如这个包安装在我的虚拟环境位置：
venv/lib/python3.4/site-packages/aliyun_python_sdk_core-2.4.4-py3.4.egg
把这个地址下aliyunsdkcore文件夹中的文件统统替换成这边下载的就行；

怎么找到这个位置？
看报错信息就知道了。

**Comment by geekil** [comment]
@kant-li 谢谢你的提醒，代码直接放项目里确实有点乱，我提了一个包到pypi，现在可以直接通过<code>pip install aliyunsdkcore</code>来安装使用，也可以使用你的方法替换原生包中不支持python3的文件为该项目中的文件。
