### ISSUE TITLE
import err

### ISSUE THREAD

**Issue by wxl200854** [duangy/aliyunsdkcore#7]
ImportError: cannot import name 'CommonRequest' from 'aliyunsdkcore.request'

**Comment by VictorZhang2014** [comment]
https://help.aliyun.com/document_detail/112147.html?spm=a2c4g.11174283.6.651.8d482c42n6uzrm

如果您使用Python 2.x，执行以下命令，安装阿里云SDK核心库：
`pip install aliyun-python-sdk-core`

如果您使用Python 3.x，执行以下命令，安装阿里云SDK核心库：
`pip install aliyun-python-sdk-core-v3`

**Comment by watchpoints** [comment]
还是不对ImportError: cannot import name 'CommonRequest' from 'aliyunsdkcore.request' (/usr/local/Python-3.10.12/lib/python3.10/site-packages/aliyunsdkcore/request.py)
